=== Minilellent/paginaclase/Proyecto Final/datos.dtd
<!ELEMENT biblioteca_steam (juego+)>

<!ELEMENT juego (titulo , desarrollador ,lanzamiento, horas_jugadas)>

<!ATTLIST juego categoria CDATA #REQUIRED>

<!ELEMENT titulo  (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT desarrollador  (#PCDATA)>
<!ELEMENT lanzamiento  (#PCDATA)>
<!ELEMENT horas_jugadas  (#PCDATA)>

=== Minilellent/paginaclase/Proyecto Final/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca_steam SYSTEM "datos.dtd">
<biblioteca_steam>
   <juego categoria="Acción FPS">
          <titulo> DOOM ETERNAL </titulo>
		  <imagen>../imagenes/Doom.webp</imagen>
		  <desarrollador> id Software </desarrollador>
		  <lanzamiento> 2020 </lanzamiento>
		  <horas_jugadas> 50,2 horas </horas_jugadas>
	 </juego> 	  
	 
   <juego categoria="Carreras Mundo-Abierto">
          <titulo> Forza Horizon 5 </titulo>
		  <imagen>../imagenes/forza.webp</imagen>
		  <desarrollador> Playground Games </desarrollador>
		  <lanzamiento>2021</lanzamiento>
		  <horas_jugadas> 94,7 horas</horas_jugadas>
	 </juego> 	 
	 
   <juego categoria="Acción Aventura">
          <titulo> God of War </titulo>
		  <imagen>../imagenes/gow.webp</imagen>
		  <desarrollador> Santa Monica Studio </desarrollador>
		  <lanzamiento> 2022 </lanzamiento>
		  <horas_jugadas>42 horas</horas_jugadas>
	 </juego> 	 
	 
   <juego categoria="Metroidvania">
          <titulo> Hollow Knight </titulo>
		  <imagen>../imagenes/hollow.webp</imagen>
		  <desarrollador> Team Cherry </desarrollador>
		  <lanzamiento> 2017 </lanzamiento>
		  <horas_jugadas> 119,1 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Metroidvania">
          <titulo> Hollow Knight: Silksong </titulo>
		  <imagen>../imagenes/hollow2.webp</imagen>
		  <desarrollador> Team Cherry </desarrollador>
		  <lanzamiento> 2025 </lanzamiento>
		  <horas_jugadas> 90,6 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Exploración Misterio">
          <titulo> Outer Wilds</titulo>
		  <imagen>../imagenes/outerwilds.webp</imagen>
		  <desarrollador> Mobius Digital </desarrollador>
		  <lanzamiento> 2020 </lanzamiento>
		  <horas_jugadas> 49,2 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria=" RPG Indie">
          <titulo> Undertale </titulo>
		  <imagen>../imagenes/undertale.webp</imagen>
		  <desarrollador> Toby Fox </desarrollador>
		  <lanzamiento> 2015 </lanzamiento>
		  <horas_jugadas> 13,5 horas </horas_jugadas>
	 </juego> 
	 
   <juego categoria="Plataformas">
          <titulo> Spyro™ Reignited Trilogy </titulo>
		  <imagen>../imagenes/spyro.webp</imagen>
		  <desarrollador> Toys for Bob</desarrollador>
		  <lanzamiento> 2019 </lanzamiento>
		  <horas_jugadas> 48,3 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Aventura Cooperativo">
          <titulo> It Takes Two </titulo>
		  <imagen>../imagenes/ittake.webp</imagen>
		  <desarrollador> Hazelight Studios </desarrollador>
		  <lanzamiento> 2021 </lanzamiento>
		  <horas_jugadas> 17,1 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Roguelike Cartas">
          <titulo> Balatro </titulo>
		  <imagen>../imagenes/bala.webp</imagen>
		  <desarrollador> LocalThunk</desarrollador>
		  <lanzamiento> 2024 </lanzamiento>
		  <horas_jugadas> 15,8 horas </horas_jugadas>
	 </juego> 	 
	 
   <juego categoria="Idle">
          <titulo> Coockie Clicker </titulo>
		  <imagen>../imagenes/coockie.webp</imagen>
		  <desarrollador> DashNet </desarrollador>
		  <lanzamiento> 2021 </lanzamiento>
		  <horas_jugadas> 229,1 horas </horas_jugadas>
	 </juego> 	 
	 
   <juego categoria="FPS Competitivo">
          <titulo> Counter Strike 2 </titulo>
		  <imagen>../imagenes/cs2.webp</imagen>
		  <desarrollador> Valve </desarrollador>
		  <lanzamiento> 2023 </lanzamiento>
		  <horas_jugadas> 35,7 horas</horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Roguelike Gestión">
          <titulo> Cult of the Lamb</titulo>
		  <imagen>../imagenes/cult.webp</imagen>
		  <desarrollador> Massive Monster </desarrollador>
		  <lanzamiento>2022</lanzamiento>
		  <horas_jugadas> 39,7 horas</horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Supervivencia Gestión">
          <titulo> Forager </titulo>
		  <imagen>../imagenes/forager.webp</imagen>
		  <desarrollador> HopFrog </desarrollador>
		  <lanzamiento> 2019 </lanzamiento>
		  <horas_jugadas> 22,3 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Roguelike Acción">
          <titulo> Hades </titulo>
		  <imagen>../imagenes/hades.webp</imagen>
		  <desarrollador> Supergiant Games</desarrollador>
		  <lanzamiento> 2020 </lanzamiento>
		  <horas_jugadas> 71,5 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria="Idle">
          <titulo> Idle Slayer </titulo>
		  <imagen>../imagenes/slayer.webp</imagen>
		  <desarrollador> Pablo Leban </desarrollador>
		  <lanzamiento> 2020 </lanzamiento>
		  <horas_jugadas> 70 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria=" Gestión Simulación">
          <titulo> Jurassic World Evolution 2 </titulo>
		  <imagen>../imagenes/jwe2.webp</imagen>
		  <desarrollador> Frontier Developments</desarrollador>
		  <lanzamiento>2021</lanzamiento>
		  <horas_jugadas> 7 horas </horas_jugadas>
	 </juego> 	
	 
   <juego categoria="MMORPG Idle">
          <titulo> Legends of Idleon MMO </titulo>
		  <imagen>../imagenes/loimmo.webp</imagen>
		  <desarrollador> Lavaflame2</desarrollador>
		  <lanzamiento> 2021 </lanzamiento>
		  <horas_jugadas> 373,8 horas </horas_jugadas>
	 </juego> 	 
	 
   <juego categoria="Gestión Simulación">
          <titulo> Stardew Valley </titulo>
		  <imagen>../imagenes/stardew.webp</imagen>
		  <desarrollador> ConcernedApe </desarrollador>
		  <lanzamiento> 2016 </lanzamiento>
		  <horas_jugadas> 409,3 horas </horas_jugadas>
	</juego> 
 
   <juego categoria="Simulación Puzle">
          <titulo>World of Guns: Gun Disassembly</titulo>
		  <imagen>../imagenes/guns.webp</imagen>
		  <desarrollador> Noble Empire Corp </desarrollador>
		  <lanzamiento> 2014 </lanzamiento>
		  <horas_jugadas> 2 horas </horas_jugadas>		

   </juego> 
</biblioteca_steam>
